server:
  port: 9090

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: survey-service
          uri: lb://SURVEY-SERVICE
          predicates:
            - Path=/survey/**
          filters:
            - StripPrefix=1
        - id: assessment-service
          uri: lb://ASSESSMENT-SERVICE
          predicates:
            - Path=/assessment/**
          filters:
            - StripPrefix=1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/